[licenses]
unlicensed = "deny"
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-DFS-2016",
    "MPL-2.0",
    "BSL-1.0",
    "BSD-3-Clause",
    "ICS"
]
copyleft = "warn"
default = "deny"
confidence-threshold = 0.8
exceptions = []
